[theme]
primaryColor = "#54a0ff"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1a1d24"
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 50

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
